CREATE TABLE IF NOT EXISTS subjects(
	subject_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	name VARCHAR(150) NOT NULL,
	teacher_id INTEGER,
	FOREIGN KEY (teacher_id) REFERENCES teachers (teacher_id)
		ON UPDATE CASCADE 
		ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS teachers(
	teacher_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	name VARCHAR(100) NOT NULL
);


CREATE TABLE IF NOT EXISTS groups(
	group_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	group_name VARCHAR(150),
	subject_id INTEGER,
	FOREIGN KEY(subject_id) REFERENCES subjects (subject_id)
		ON UPDATE CASCADE
		ON DELETE SET NULL
);


CREATE TABLE IF NOT EXISTS students(
	student_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	name VARCHAR(100) NOT NULL,
	birthday DATETIME DEFAULT (CURRENT_TIMESTAMP),
	group_id INTEGER,
	FOREIGN KEY(group_id) REFERENCES groups (group_id)
		ON UPDATE CASCADE
		ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS grades(
	grade_id  INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	grade SMALLINT UNSIGNED,
	student_id INTEGER,
	subject_id INTEGER,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	FOREIGN KEY(subject_id) REFERENCES subjects (subject_id)
		ON UPDATE CASCADE
		ON DELETE SET NULL,
	FOREIGN KEY(student_id) REFERENCES students (student_id)
		ON UPDATE CASCADE
		ON DELETE CASCADE
);


