[tool.poetry]
name = "goit-pyweb-6"
version = "0.1.0"
description = ""
authors = ["DeLight <nazarchukyayko@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
faker = "^28.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
